version: '2'

services:
  api: # Node.js App
    container_name: node-api
    build: .
    ports:
      - "3000:3000" # Expose API port
    environment: # Set ENV vars
     - PORT=3000
    volumes: # Attach local book data directory
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development